### ISSUE TITLE
Add node() to public API of RNode

### ISSUE THREAD

**Issue by hannesN** [BestSolution-at/FX-Test#25]
Tobe able to test Custom Panes (lie a GEF viewer) it would be nice to be able to access the wrapped node of an RNode to be able to ask for Node-specific properties.

In my current case I want to check the label of a button to filter buttons without an ID or want to check the number and state of rows in a TableTreeView.

**Comment by tomsontom** [comment]
I think the API is already there
https://github.com/BestSolution-at/FX-Test/blob/fbde9137193c4606873ad2142a81b8a3711fe2ec/at.bestsolution.fx.test/at.bestsolution.fx.test.rcontrol/src/main/java/at/bestsolution/fx/test/rcontrol/RNode.java#L31
