### ISSUE TITLE
Update site http://downloads.foss.bestsolution.at/fx-test/releases/0.0.1/repository/ down

### ISSUE THREAD

**Issue by vogella** [BestSolution-at/FX-Test#27]
The update site http://downloads.foss.bestsolution.at/fx-test/releases/0.0.1/repository/ appears to be down. Do you have a new update site?

**Comment by daudo** [comment]
fixed, thx for the notice

**Comment by tomsontom** [comment]
Upsite is up once more! Please note that we started moving this partially to e(fx)clipse itself - but it is not yet published as an update-site - https://github.com/eclipse-efx/efxclipse-rt/tree/3.x/modules/test

**Comment by vogella** [comment]
Thanks for the fast fix

Am Mo., 7. Jan. 2019, 10:33 hat Tom Schindl <notifications@github.com>
geschrieben:
